name: Continuous build

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-continuous:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    uses: boku-engineering/github-actions-continuous-build/.github/workflows/maven-snapshot-build.yaml@v1
    with:
      branch: master
      java-version: 17
    secrets:
      registry-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}