name: Continuous build on release branch

on:
  push:
    branches:
      - 'release/*'
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to build (should start with \"release/\")"
        required: true

permissions:
  contents: read

jobs:
  build-continuous-branch:
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.branch || github.ref }}
      cancel-in-progress: true

    uses: boku-engineering/github-actions-continuous-build/.github/workflows/maven-snapshot-build.yaml@v1
    with:
      branch: ${{ inputs.branch || github.ref }}
      java-version: 17
    secrets:
      registry-username: ${{ secrets.ARTIFACTORY_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}